# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ropa en Conjunto
email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Jekyll theme. It is designed for business purpose and ported by 
  Melvin Ch'ng.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Company Information
company_name: Ropa en Conjunto!    
address_line: Aztecas 5, Morelos, Cuauhtémoc, 06000 Ciudad de México, CDMX
telephone_number: 55.39.56.31.18
fax_number: 55.83.25.26.70
company_email: joshuahernandezamaro123@gmail.com
google_map: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d940.5749036441772!2d-99.12921113382667!3d19.442644861645167!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1f930d5ab5f69%3A0xbb9d4c66b7b4df5d!2sMercado%20de%20Granaditas!5e0!3m2!1sen!2smx!4v1683595733999!5m2!1sen!2smx
#google_map: https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d3618.727010735933!2d91.837871!3d24.907291700000002!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2s!4v1404919738144
#<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d940.5749036441772!2d-99.12921113382667!3d19.442644861645167!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1f930d5ab5f69%3A0xbb9d4c66b7b4df5d!2sMercado%20de%20Granaditas!5e0!3m2!1sen!2smx!4v1683595733999!5m2!1sen!2smx" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
# Social Link
facebook_link: 
twitter_link: http://www.twitter.com
linkedin_link: http://www.linkedin.com
googleplus_link: http://plus.google.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
